# Generated by Django 6.1.1 on 2026-09-12 07:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('name', models.CharField(help_text='Campus name', max_length=255)),
                ('code', models.CharField(db_index=True, help_text="Campus identifier code, unique within organization (e.g., 'ENG', 'MED')", max_length=50)),
                ('timezone', models.CharField(default='UTC', help_text="Local timezone identifier (e.g., 'Asia/Kolkata', 'UTC')", max_length=50)),
                ('address', models.JSONField(blank=True, default=dict, help_text='Structured physical address details')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', help_text='Operational status of this campus', max_length=32)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campuses',
                'db_table': 'campuses',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('name', models.CharField(help_text='Institutional name', max_length=255)),
                ('slug', models.SlugField(help_text='Globally unique institutional identifier slug', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated')], db_index=True, default='ACTIVE', help_text='Lifecycle status of the organization', max_length=32)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('codename', models.CharField(db_index=True, help_text="Machine-readable capability identifier (e.g., 'incident:create')", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable permission label', max_length=255)),
                ('module', models.CharField(db_index=True, help_text="Functional module domain (e.g., 'incident', 'task', 'safety', 'auth')", max_length=100)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permissions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='User unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Institutional or platform email address', max_length=255)),
                ('full_name', models.CharField(help_text='Legal or display full name', max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', help_text='Contact telephone number', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this user account is active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether user can access Django admin site')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Account creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('primary_campus', models.ForeignKey(blank=True, help_text='Primary campus of residence/operation for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.campus')),
                ('organization', models.ForeignKey(blank=True, help_text='Institutional organization owning this user account', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.organization')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='campus',
            name='organization',
            field=models.ForeignKey(help_text='Parent organization owning this campus', on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='core.organization'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique audit record identifier (UUID v4)', primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('USER', 'User'), ('SYSTEM', 'System'), ('AGENT', 'Agent')], db_index=True, default='USER', help_text='Type of actor (USER, SYSTEM, AGENT)', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Originating IP address of the caller', null=True)),
                ('action', models.CharField(db_index=True, help_text="Action verb (e.g., 'auth.login', 'auth.failed', 'user.create', 'role.update')", max_length=100)),
                ('entity_type', models.CharField(db_index=True, help_text="Target entity class name (e.g., 'User', 'Campus', 'Role')", max_length=100)),
                ('entity_id', models.CharField(db_index=True, help_text='Target entity primary key identifier', max_length=100)),
                ('pre_state_json', models.JSONField(blank=True, default=dict, help_text='State snapshot before the action occurred')),
                ('post_state_json', models.JSONField(blank=True, default=dict, help_text='State snapshot after the action occurred')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the action was recorded')),
                ('actor', models.ForeignKey(blank=True, help_text='User initiating the action (null for system/unauthenticated events)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(blank=True, help_text='Campus context for this event if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.campus')),
                ('organization', models.ForeignKey(blank=True, help_text='Institutional organization context for this event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.organization')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('name', models.CharField(db_index=True, help_text="Role identifier name (e.g., 'STUDENT', 'CAMPUS_ADMIN')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of role responsibilities and privileges')),
                ('is_system_role', models.BooleanField(db_index=True, default=False, help_text='Flag indicating platform-protected immutable system role')),
                ('organization', models.ForeignKey(blank=True, help_text='Owning organization; null for platform-wide system roles', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.organization')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Granular permissions granted to holders of this role', related_name='roles', to='core.permission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='RBAC roles assigned to this user', related_name='users', to='core.role'),
        ),
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_organization_campus_code'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'campus', '-created_at'], name='audit_logs_organiz_ca8b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='audit_logs_action_bcaa71_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system_role', True)), fields=('name',), name='unique_system_role_name'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system_role', False)), fields=('organization', 'name'), name='unique_organization_role_name'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'email'), name='unique_organization_user_email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('email',), name='unique_system_user_email'),
        ),
    ]
