# Generated by Django 6.1.1 on 2026-09-12 08:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('name', models.CharField(help_text='Building name', max_length=255)),
                ('code', models.CharField(db_index=True, help_text="Building code, unique per campus (e.g., 'ENG-B', 'LIB')", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Building description and location details')),
                ('floors_count', models.PositiveIntegerField(default=1, help_text='Number of physical levels above or below ground')),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('RENOVATION', 'Renovation'), ('DECOMMISSIONED', 'Decommissioned')], db_index=True, default='OPERATIONAL', help_text='Building operational status', max_length=32)),
                ('gis_data', models.JSONField(blank=True, default=dict, help_text='Geographic coordinates, polygon boundary, or GIS coordinates')),
                ('campus', models.ForeignKey(blank=True, help_text='Owning campus if campus-scoped', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.campus')),
                ('organization', models.ForeignKey(help_text='Owning organization for multi-tenancy', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'db_table': 'buildings',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('name', models.CharField(help_text='Department name', max_length=255)),
                ('code', models.CharField(db_index=True, help_text="Department code, unique per campus (e.g., 'IT', 'MAINTENANCE')", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of department responsibilities')),
                ('contact_email', models.EmailField(blank=True, help_text='Primary departmental contact email', max_length=254)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', help_text='Department operational status', max_length=32)),
                ('campus', models.ForeignKey(blank=True, help_text='Owning campus if campus-scoped', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.campus')),
                ('escalation_contact', models.ForeignKey(blank=True, help_text='Designated escalation contact / manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Owning organization for multi-tenancy', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('floor_number', models.IntegerField(help_text='Numeric floor index (e.g. -1 for basement, 0 for ground, 1 for 1st floor)')),
                ('label', models.CharField(help_text="Human-readable floor designation (e.g. 'Basement', 'Ground Floor', '2nd Floor')", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Floor layout notes or facilities')),
                ('building', models.ForeignKey(help_text='Parent building containing this floor', on_delete=django.db.models.deletion.PROTECT, related_name='floors', to='core.building')),
                ('campus', models.ForeignKey(blank=True, help_text='Owning campus if campus-scoped', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.campus')),
                ('organization', models.ForeignKey(help_text='Owning organization for multi-tenancy', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
            ],
            options={
                'verbose_name': 'Floor',
                'verbose_name_plural': 'Floors',
                'db_table': 'floors',
                'ordering': ['building', 'floor_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('room_number', models.CharField(db_index=True, help_text="Room number or code (e.g. '101', 'LAB-204')", max_length=50)),
                ('name', models.CharField(blank=True, help_text="Descriptive room name (e.g. 'Computer Networks Laboratory')", max_length=255)),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('LAB', 'Laboratory'), ('OFFICE', 'Office'), ('SEMINAR_HALL', 'Seminar Hall'), ('HOSTEL_ROOM', 'Hostel Room'), ('UTILITY', 'Utility / Service'), ('MESS', 'Mess / Dining Hall')], db_index=True, default='CLASSROOM', help_text='Room categorization', max_length=32)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Max seating/standing occupant capacity')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('UNDER_MAINTENANCE', 'Under Maintenance')], db_index=True, default='AVAILABLE', help_text='Room operational availability', max_length=32)),
                ('building', models.ForeignKey(help_text='Parent building containing this room', on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='core.building')),
                ('campus', models.ForeignKey(blank=True, help_text='Owning campus if campus-scoped', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.campus')),
                ('floor', models.ForeignKey(help_text='Specific floor level containing this room', on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='core.floor')),
                ('organization', models.ForeignKey(help_text='Owning organization for multi-tenancy', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'ordering': ['building', 'floor', 'room_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('name', models.CharField(help_text='Asset display name', max_length=255)),
                ('asset_tag', models.CharField(db_index=True, help_text="Campus-unique barcode/asset identifier (e.g. 'AST-AP-004')", max_length=100)),
                ('serial_number', models.CharField(blank=True, help_text='Manufacturer hardware serial number', max_length=100)),
                ('category', models.CharField(choices=[('NETWORKING', 'Networking & IT'), ('HVAC', 'HVAC & Climate'), ('ELECTRICAL', 'Electrical & Power'), ('PLUMBING', 'Plumbing & Sanitation'), ('SECURITY_EQUIPMENT', 'Security & Surveillance'), ('FURNITURE', 'Furniture & Fixtures'), ('GENERAL', 'General Equipment')], db_index=True, default='GENERAL', help_text='Asset classification category', max_length=32)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('DEGRADED', 'Degraded Performance'), ('OUT_OF_SERVICE', 'Out of Service'), ('RETIRED', 'Retired')], db_index=True, default='OPERATIONAL', help_text='Operational condition of the asset', max_length=32)),
                ('install_date', models.DateField(blank=True, help_text='Date the asset was commissioned or installed', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Technical specifications, vendor details, IP/MAC addresses')),
                ('campus', models.ForeignKey(blank=True, help_text='Owning campus if campus-scoped', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.campus')),
                ('organization', models.ForeignKey(help_text='Owning organization for multi-tenancy', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
                ('building', models.ForeignKey(blank=True, help_text='Building where the asset is installed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='core.building')),
                ('department', models.ForeignKey(help_text='Department responsible for maintaining this asset', on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='core.department')),
                ('floor', models.ForeignKey(blank=True, help_text='Floor where the asset is installed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='core.floor')),
                ('room', models.ForeignKey(blank=True, help_text='Specific room containing this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='core.room')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'db_table': 'assets',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['organization', 'campus'], name='buildings_organiz_866f83_idx'),
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(fields=('campus', 'code'), name='unique_campus_building_code'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['organization', 'campus'], name='departments_organiz_763c7a_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('campus', 'code'), name='unique_campus_department_code'),
        ),
        migrations.AddIndex(
            model_name='floor',
            index=models.Index(fields=['organization', 'campus'], name='floors_organiz_4189bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('building', 'floor_number'), name='unique_building_floor_number'),
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('building', 'label'), name='unique_building_floor_label'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['organization', 'campus'], name='rooms_organiz_bec7fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('floor', 'room_number'), name='unique_floor_room_number'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'campus'], name='assets_organiz_936685_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('campus', 'asset_tag'), name='unique_campus_asset_tag'),
        ),
    ]
