# Generated by Django 6.1.1 on 2026-09-14 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_building_department_floor_room_asset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('title', models.CharField(help_text='Brief summary of the issue', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the incident / issue')),
                ('category', models.CharField(choices=[('IT_NETWORK', 'IT & Networking'), ('ELECTRICAL', 'Electrical & Power'), ('PLUMBING', 'Plumbing & Sanitation'), ('HVAC', 'HVAC & Climate'), ('SAFETY', 'Safety & Security'), ('FACILITY', 'Facilities & Infrastructure'), ('OTHER', 'Other / General')], db_index=True, default='OTHER', help_text='Functional operational category', max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', help_text='Operational priority / urgency', max_length=32)),
                ('status', models.CharField(choices=[('INGESTED', 'Ingested'), ('TRIAGING', 'Triaging'), ('PENDING_APPROVAL', 'Pending Approval'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('VERIFIED', 'Verified'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened'), ('REJECTED', 'Rejected'), ('DUPLICATE_LINKED', 'Duplicate Linked')], db_index=True, default='INGESTED', help_text='Current lifecycle state', max_length=32)),
                ('source', models.CharField(choices=[('WEB', 'Web Portal'), ('MOBILE', 'Mobile App'), ('KIOSK', 'Campus Kiosk'), ('API', 'External API'), ('SYSTEM', 'System Automated')], default='WEB', help_text='Ingestion channel', max_length=32)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes explaining how the issue was resolved')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when the issue was resolved', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of soft deletion (null for active records)', null=True)),
                ('asset', models.ForeignKey(blank=True, help_text='Specific equipment / asset impacted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.asset')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Assigned staff member / handler', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('building', models.ForeignKey(blank=True, help_text='Building where the issue occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.building')),
                ('campus', models.ForeignKey(blank=True, help_text='Owning campus if campus-scoped', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.campus')),
                ('department', models.ForeignKey(blank=True, help_text='Responsible functional department (e.g. IT, Facilities)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.department')),
                ('floor', models.ForeignKey(blank=True, help_text='Floor level where the issue occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.floor')),
                ('is_duplicate_of', models.ForeignKey(blank=True, help_text='Master incident if this report is a confirmed duplicate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='core.incident')),
                ('organization', models.ForeignKey(help_text='Owning organization for multi-tenancy', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
                ('reporter', models.ForeignKey(help_text='User who reported the incident', on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, help_text='Room / space where the issue occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.room')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'db_table': 'incidents',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('event_type', models.CharField(choices=[('REPORTED', 'Reported'), ('STATUS_CHANGED', 'Status Changed'), ('PRIORITY_CHANGED', 'Priority Changed'), ('CATEGORY_CHANGED', 'Category Changed'), ('ASSIGNMENT_CHANGED', 'Assignment Changed'), ('LOCATION_CHANGED', 'Location Changed'), ('DUPLICATE_MARKED', 'Marked as Duplicate'), ('RESOLVED', 'Resolved'), ('VERIFIED', 'Verified'), ('REOPENED', 'Reopened'), ('CLOSED', 'Closed'), ('COMMENT_ADDED', 'Comment Added')], db_index=True, help_text='Type of operational event', max_length=50)),
                ('description', models.TextField(help_text='Human-readable event summary or log entry')),
                ('actor_type', models.CharField(choices=[('USER', 'User'), ('SYSTEM', 'System'), ('AGENT', 'Agent')], db_index=True, default='USER', help_text='Type of actor (USER, SYSTEM, AGENT)', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured event payload (e.g. from_status, to_status)')),
                ('request_id', models.CharField(blank=True, db_index=True, help_text='Client or HTTP request correlation ID', max_length=100)),
                ('actor', models.ForeignKey(blank=True, help_text='User who initiated this event (null for system/agent actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_events', to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(blank=True, help_text='Owning campus if campus-scoped', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.campus')),
                ('incident', models.ForeignKey(help_text='Parent incident', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.incident')),
                ('organization', models.ForeignKey(help_text='Owning organization for multi-tenancy', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
            ],
            options={
                'verbose_name': 'Incident Event',
                'verbose_name_plural': 'Incident Events',
                'db_table': 'incident_events',
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['campus', 'status', '-created_at'], name='idx_incidents_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['campus', 'category', 'priority'], name='idx_incidents_tenant_cat_prio'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['campus', 'reporter'], name='idx_incidents_tenant_reporter'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['campus', 'building'], name='idx_incidents_tenant_building'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['campus', 'department'], name='idx_incidents_tenant_dept'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.CheckConstraint(condition=models.Q(('is_duplicate_of', models.F('id')), _negated=True), name='check_incident_not_self_duplicate'),
        ),
        migrations.AddIndex(
            model_name='incidentevent',
            index=models.Index(fields=['incident', '-created_at'], name='idx_incident_events_timeline'),
        ),
        migrations.AddIndex(
            model_name='incidentevent',
            index=models.Index(fields=['campus', 'event_type'], name='idx_incident_events_type'),
        ),
    ]
