# Generated by Django 6.1.1 on 2026-09-14 18:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_incident_incidentevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('name', models.CharField(help_text='Human-readable policy name (e.g. Critical Hardware Outage SLA)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of SLA scope and operational terms')),
                ('priority', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, help_text='Applicable incident/task priority level (None for universal)', max_length=32, null=True)),
                ('task_type', models.CharField(blank=True, db_index=True, help_text='Applicable task type (None for universal)', max_length=50, null=True)),
                ('category', models.CharField(blank=True, choices=[('IT_NETWORK', 'IT & Networking'), ('ELECTRICAL', 'Electrical & Power'), ('PLUMBING', 'Plumbing & Sanitation'), ('HVAC', 'HVAC & Climate'), ('SAFETY', 'Safety & Security'), ('FACILITY', 'Facilities & Infrastructure'), ('OTHER', 'Other / General')], db_index=True, help_text='Applicable operational domain category (None for universal)', max_length=50, null=True)),
                ('response_target', models.DurationField(help_text='Target duration to respond / begin work on the task')),
                ('resolution_target', models.DurationField(help_text='Target duration to complete the task work')),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Whether this SLA policy is actively applied to new tasks')),
                ('campus', models.ForeignKey(blank=True, help_text='Owning campus if campus-scoped', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.campus')),
                ('organization', models.ForeignKey(help_text='Owning organization for multi-tenancy', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
            ],
            options={
                'verbose_name': 'SLA',
                'verbose_name_plural': 'SLAs',
                'ordering': ['priority', 'resolution_target'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('title', models.CharField(help_text='Clear, actionable title of the operational task', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed instructions or context for the assigned technician')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', help_text='Current lifecycle state', max_length=32)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', help_text='Operational urgency / priority', max_length=32)),
                ('task_type', models.CharField(choices=[('INSPECTION', 'Inspection & Diagnostics'), ('REPAIR', 'Repair & Fix'), ('MAINTENANCE', 'Preventative Maintenance'), ('COMMUNICATION', 'Student/Faculty Communication'), ('ESCALATION', 'Administrative Escalation'), ('FOLLOW_UP', 'Follow-up Verification'), ('OTHER', 'Other Operational Work')], db_index=True, default='OTHER', help_text='Typed category of work to be performed', max_length=50)),
                ('due_at', models.DateTimeField(blank=True, help_text='Resolution deadline calculated by the SLA engine', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='Timestamp when technician initiated work (transition to IN_PROGRESS)', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when technician completed all required work', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Timestamp when task was cancelled before completion', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured operational telemetry, tool parameters, or checklist states')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp for soft-deletion', null=True)),
                ('assigned_department', models.ForeignKey(blank=True, help_text='Assigned campus service unit / department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='core.department')),
                ('assigned_user', models.ForeignKey(blank=True, help_text='Assigned operational technician / specialist', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(blank=True, help_text='Owning campus if campus-scoped', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.campus')),
                ('created_by', models.ForeignKey(help_text='User (admin, dispatcher, or system) who initiated this task', on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(help_text='Parent operational incident that spawned this task', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.incident')),
                ('organization', models.ForeignKey(help_text='Owning organization for multi-tenancy', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
                ('sla', models.ForeignKey(blank=True, help_text='Governing SLA policy applied to this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.sla')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SLATracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when SLA monitoring commenced')),
                ('response_due_at', models.DateTimeField(help_text='Authoritative deadline for response/acknowledgement')),
                ('resolution_due_at', models.DateTimeField(help_text='Authoritative deadline for task resolution/completion')),
                ('response_completed_at', models.DateTimeField(blank=True, help_text='Timestamp when task response requirement was met (started work)', null=True)),
                ('resolution_completed_at', models.DateTimeField(blank=True, help_text='Timestamp when task completion requirement was met', null=True)),
                ('response_breached_at', models.DateTimeField(blank=True, help_text='Timestamp when response deadline was breached', null=True)),
                ('resolution_breached_at', models.DateTimeField(blank=True, help_text='Timestamp when resolution deadline was breached', null=True)),
                ('state', models.CharField(choices=[('HEALTHY', 'Healthy'), ('AT_RISK', 'At Risk'), ('BREACHED', 'Breached'), ('MET', 'Met')], db_index=True, default='HEALTHY', help_text='Current deterministic SLA compliance status', max_length=32)),
                ('campus', models.ForeignKey(blank=True, help_text='Owning campus if campus-scoped', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.campus')),
                ('organization', models.ForeignKey(help_text='Owning organization for multi-tenancy', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
                ('sla', models.ForeignKey(help_text='Authoritative SLA policy applied to this task', on_delete=django.db.models.deletion.PROTECT, related_name='trackings', to='core.sla')),
                ('task', models.OneToOneField(help_text='Task being monitored by this SLA tracking instance', on_delete=django.db.models.deletion.CASCADE, related_name='sla_tracking', to='core.task')),
            ],
            options={
                'verbose_name': 'SLA Tracking',
                'verbose_name_plural': 'SLA Trackings',
            },
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('event_type', models.CharField(choices=[('CREATED', 'Task Created'), ('ASSIGNED', 'Assigned'), ('REASSIGNED', 'Reassigned'), ('STARTED', 'Work Started'), ('BLOCKED', 'Blocked'), ('UNBLOCKED', 'Unblocked'), ('SLA_WARNING', 'SLA At Risk Warning'), ('SLA_BREACHED', 'SLA Deadline Breached'), ('COMPLETED', 'Task Completed'), ('CANCELLED', 'Task Cancelled'), ('COMMENTED', 'Comment Added')], db_index=True, help_text='Type of operational event', max_length=50)),
                ('actor_type', models.CharField(choices=[('USER', 'User'), ('SYSTEM', 'System'), ('AGENT', 'Agent')], default='USER', help_text='Actor classification (USER, SYSTEM, or AGENT)', max_length=32)),
                ('from_status', models.CharField(blank=True, help_text='Previous task status before this event', max_length=32)),
                ('to_status', models.CharField(blank=True, help_text='New task status after this event', max_length=32)),
                ('message', models.TextField(blank=True, help_text='Human-readable description, notes, or resolution comments')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured event context')),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered this event (null if automated or system)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(blank=True, help_text='Owning campus if campus-scoped', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.campus')),
                ('organization', models.ForeignKey(help_text='Owning organization for multi-tenancy', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
                ('task', models.ForeignKey(help_text='Task to which this timeline event belongs', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.task')),
            ],
            options={
                'verbose_name': 'Task Event',
                'verbose_name_plural': 'Task Events',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sla',
            index=models.Index(fields=['organization', 'campus', 'active'], name='core_sla_organiz_645093_idx'),
        ),
        migrations.AddIndex(
            model_name='sla',
            index=models.Index(fields=['priority', 'category', 'active'], name='core_sla_priorit_a97e83_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization', 'campus', 'status'], name='core_task_organiz_e391a7_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['incident', 'status'], name='core_task_inciden_b6bc99_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_user', 'status'], name='core_task_assigne_0c8b06_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_department', 'status'], name='core_task_assigne_2905b2_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_at', 'status'], name='core_task_due_at_c1bc10_idx'),
        ),
        migrations.AddIndex(
            model_name='slatracking',
            index=models.Index(fields=['organization', 'campus', 'state'], name='core_slatra_organiz_52bbf2_idx'),
        ),
        migrations.AddIndex(
            model_name='slatracking',
            index=models.Index(fields=['resolution_due_at', 'state'], name='core_slatra_resolut_089855_idx'),
        ),
        migrations.AddIndex(
            model_name='taskevent',
            index=models.Index(fields=['task', 'created_at'], name='core_taskev_task_id_1b6344_idx'),
        ),
        migrations.AddIndex(
            model_name='taskevent',
            index=models.Index(fields=['event_type', 'created_at'], name='core_taskev_event_t_d4e12f_idx'),
        ),
    ]
