# Generated by Django 6.1.1 on 2026-09-15 14:14

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from pgvector.django import VectorExtension
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sla_task_slatracking_taskevent_and_more'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='OperationalInsight',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique insight identifier', primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('RECURRING_ASSET_FAILURE', 'Recurring Asset Failure'), ('LOCATION_HOTSPOT', 'Location Incident Hotspot'), ('CROSS_CIRCUIT_CASCADE', 'Cross-Circuit Power Cascade')], db_index=True, help_text='Classification of the operational anomaly', max_length=50)),
                ('fact_summary', models.TextField(help_text='Empirical verifiable facts: timestamps, incident IDs, downtime measurements')),
                ('inference_analysis', models.TextField(help_text='Probabilistic deductions: pattern analysis, suspected degradation mechanisms')),
                ('recommendation', models.TextField(help_text='Actionable suggestions for human operational personnel')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Calculated algorithmic confidence score (0.0 to 1.0)')),
                ('window_start', models.DateTimeField(help_text='Start timestamp of the observation window')),
                ('window_end', models.DateTimeField(help_text='End timestamp of the observation window')),
                ('incident_count', models.PositiveIntegerField(default=0, help_text='Number of empirical incidents contributing to this insight')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Concern'), ('ACKNOWLEDGED', 'Acknowledged by Facility Staff'), ('RESOLVED', 'Remediated / Verified')], db_index=True, default='ACTIVE', help_text='Current operational review status', max_length=32)),
                ('campus', models.ForeignKey(blank=True, help_text='Owning campus if campus-scoped', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.campus')),
                ('organization', models.ForeignKey(help_text='Owning organization for multi-tenancy', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
                ('target_asset', models.ForeignKey(blank=True, help_text='Impacted equipment if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_insights', to='core.asset')),
                ('target_building', models.ForeignKey(blank=True, help_text='Impacted building if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_insights', to='core.building')),
                ('target_room', models.ForeignKey(blank=True, help_text='Impacted room if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_insights', to='core.room')),
            ],
            options={
                'db_table': 'operational_insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationalInsightIncidentEvidence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relevance_score', models.FloatField(default=1.0, help_text='Relative contribution weight of this incident to the insight')),
                ('evidence_notes', models.TextField(blank=True, help_text='Optional diagnostic notes linking this incident to the recurring pattern')),
                ('campus', models.ForeignKey(blank=True, help_text='Owning campus if campus-scoped', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.campus')),
                ('incident', models.ForeignKey(help_text='Empirical incident evidence record', on_delete=django.db.models.deletion.CASCADE, related_name='insight_evidence_links', to='core.incident')),
                ('insight', models.ForeignKey(help_text='Parent operational insight', on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='core.operationalinsight')),
                ('organization', models.ForeignKey(help_text='Owning organization for multi-tenancy', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
            ],
            options={
                'db_table': 'operational_insight_evidence',
            },
        ),
        migrations.AddField(
            model_name='operationalinsight',
            name='incidents',
            field=models.ManyToManyField(help_text='Relational evidence incidents supporting this insight', related_name='contributed_insights', through='core.OperationalInsightIncidentEvidence', to='core.incident'),
        ),
        migrations.CreateModel(
            name='OperationalMemoryChunk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique memory chunk identifier', primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('INCIDENT', 'Resolved Incident'), ('TASK', 'Completed Task'), ('ASSET', 'Campus Asset Specification')], db_index=True, help_text='Type of operational source', max_length=50)),
                ('source_id', models.CharField(db_index=True, help_text='Primary key identifier of source entity in Django Core', max_length=64)),
                ('source_version', models.PositiveIntegerField(default=1, help_text='Monotonically increasing version counter for change detection')),
                ('source_updated_at', models.DateTimeField(help_text='Timestamp of source record when this memory chunk was generated')),
                ('title', models.CharField(help_text='Brief headline for the memory chunk', max_length=255)),
                ('canonical_text', models.TextField(help_text='Normalized canonical text representation embedded into vector space')),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 hash of canonical_text for change detection and idempotency', max_length=64)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768, help_text='Dense 768-dimensional float embedding vector')),
                ('embedding_provider', models.CharField(default='mock', help_text='AI Provider used to compute embedding (e.g. mock, google, openai)', max_length=50)),
                ('embedding_model', models.CharField(default='mock-paraxis-v1', help_text='Model name used for vectorization', max_length=100)),
                ('category', models.CharField(blank=True, db_index=True, help_text='Operational domain category', max_length=50)),
                ('metadata_payload', models.JSONField(blank=True, default=dict, help_text='Structured operational metadata (downtime, technician, resolution milestones)')),
                ('asset', models.ForeignKey(blank=True, help_text='Optional campus infrastructure asset anchor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_chunks', to='core.asset')),
                ('building', models.ForeignKey(blank=True, help_text='Optional physical building anchor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_chunks', to='core.building')),
                ('campus', models.ForeignKey(blank=True, help_text='Owning campus if campus-scoped', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.campus')),
                ('organization', models.ForeignKey(help_text='Owning organization for multi-tenancy', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
                ('room', models.ForeignKey(blank=True, help_text='Optional physical room anchor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_chunks', to='core.room')),
            ],
            options={
                'db_table': 'operational_memory_chunks',
            },
        ),
        migrations.AddConstraint(
            model_name='operationalinsightincidentevidence',
            constraint=models.UniqueConstraint(fields=('insight', 'incident'), name='unique_insight_incident_evidence'),
        ),
        migrations.AddIndex(
            model_name='operationalmemorychunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='op_mem_hnsw_cosine_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='operationalmemorychunk',
            index=models.Index(fields=['organization', 'campus', 'source_type'], name='operational_organiz_0fb65f_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalmemorychunk',
            index=models.Index(fields=['organization', 'campus', 'category'], name='operational_organiz_2d1d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalmemorychunk',
            index=models.Index(fields=['organization', 'campus', 'asset'], name='operational_organiz_de8c48_idx'),
        ),
        migrations.AddConstraint(
            model_name='operationalmemorychunk',
            constraint=models.UniqueConstraint(fields=('organization', 'campus', 'source_type', 'source_id'), name='unique_tenant_campus_memory_source'),
        ),
    ]
